### ISSUE TITLE
Improve MCU approach - trello

### ISSUE THREAD

**Issue by ricardojlrufino** [reesvarney/OpenChat#16]
"Currently, I also do not see any way of syncing users between socket io and peerjs so a native implementation would allow for a much smoother system" ... you can extens peerjs server to add custom functions.

See:
Combining with existing express app
https://github.com/peers/peerjs-server

**Comment by reesvarney** [comment]
I assume you mean the custom ID generation? I saw this however I'm not too sure how I'd go about connecting this with the `req` object to link the IDs between express/ passport and peerjs. It is already setup as an `expressPeerServer` but I don't think this gives me any access to these objects. If you have any idea though please let me know.
